Update django-autoslug to v1.9.3
It solves an incompatibility with Django 1.8. I think that in Django 1.8 the
prop `model._meta.module_name` was replaced by: `model._meta.model_name`.

This was the error I saw:

```
File "/Users/jesus/fpr-admin.env/lib/python2.7/site-packages/autoslug/fields.py", line 221, in pre_save
    slug = instance._meta.module_name
AttributeError: 'Options' object has no attribute 'module_name'
```